name: Obsługa wyświetlaczy i2c HAOS
version: 1.0.5.178-RC
description: Obsługa wyświetlaczy i2c HAOS
arch:
  - aarch64
startup: services
boot: auto
devices:
  - /dev/i2c-1
  - /dev/i2c-13
url: https://github.com/KrystianPietron/i2c-addon
slug: addon-i2c
image: ghcr.io/krystianpietron/i2c-addon
privileged:
  - SYS_RAWIO
init: true
options:
  startLogo: true
  token: tokenTest
  dev-i2c-1-bus: true
  display1_dev1_enable: true
  display1_dev1_startAnimation: true
  display2_dev1_enable: true
  display2_dev1_startAnimation: true
  dev-i2c-13-bus: true
  display1_dev13_enable: true
  display1_dev13_startAnimation: true
  display2_dev13_enable: true
  display2_dev13_startAnimation: true
schema:
  startLogo: bool
  token: str
  dev-i2c-1-bus: bool
  display1_dev1_enable: bool
  display1_dev1_startAnimation: bool
  display2_dev1_enable: bool
  display2_dev1_startAnimation: bool
  dev-i2c-13-bus: bool
  display1_dev13_enable: bool
  display1_dev13_startAnimation: bool
  display2_dev13_enable: bool
  display2_dev13_startAnimation: bool