name: Obsługa wyświetlaczy i2c HAOS
version: 1.0.5.150-RC
description: Obsługa wyświetlaczy i2c HAOS
arch:
  - aarch64
startup: services
boot: auto
devices:
  - /dev/i2c-1
  - /dev/i2c-13
  - /dev/i2c-14
  - /dev/i2c-15
url: https://github.com/KrystianPietron/i2c-addon
slug: addon-i2c
image: ghcr.io/krystianpietron/i2c-addon
privileged:
  - SYS_RAWIO
init: true
options:
  token: tokenTest
  dev-i2c-1-bus:
    - display1:
        - enable: true
        - startAnimation: true
    - display2:
        - enable: true
        - startAnimation: true
  dev-i2c-13-bus:
    - display1:
        - enable: true
        - startAnimation: true
    - display2:
        - enable: true
        - startAnimation: true
schema:
  token: str
  dev-i2c-1-bus:
    - display1:
      - enable: bool
      - startAnimation: bool
    - display2:
      - enable: bool
      - startAnimation: bool
  dev-i2c-13-bus:
    - display1:
      - enable: bool
      - startAnimation: bool
    - display2:
      - enable: bool
      - startAnimation: bool