name: Build and Publish Addon

on:
  push:
    branches:
      - main
    paths:
      - 'addon-i2c/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # NOWY KROK: Ustawienie nazwy właściciela repozytorium na małe litery
      - name: Set lowercase repository owner
        id: set_repo_owner_lowercase
        run: echo "REPO_OWNER_LOWERCASE=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Get addon version from config.json
        id: get_version
        run: |
          ADDON_VERSION=$(jq -r '.version' addon-i2c/config.json)
          echo "ADDON_VERSION=$ADDON_ENV" >> $GITHUB_ENV # Poprawka: tutaj powinno być $ADDON_VERSION
        shell: bash

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./addon-i2c
          file: ./addon-i2c/Dockerfile
          platforms: linux/aarch64,linux/amd64,linux/armhf,linux/armv7
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/i2c-addon:${{ env.ADDON_VERSION }}
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/i2c-addon:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
