name: Build and Publish Addon

on:
  push:
    branches:
      - main # Uruchamia workflow przy pushu do gałęzi 'main'
    paths:
      - 'addon-i2c/**' # Uruchamia tylko jeśli pliki w folderze addon-i2c zostaną zmienione
  workflow_dispatch: # Pozwala na ręczne uruchamianie workflowu z interfejsu GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    # USUNIĘTO: strategy.matrix.arch - nie potrzebujemy już macierzy dla architektur,
    # ponieważ build-push-action zajmie się tym w jednym kroku.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Pobiera kod z repozytorium

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Konfiguruje Buildx do budowania multi-arch

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Używa wbudowanego tokena GitHub

      - name: Get addon version from config.json
        id: get_version
        run: |
          ADDON_VERSION=$(jq -r '.version' addon-i2c/config.json)
          echo "ADDON_VERSION=$ADDON_VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./addon-i2c # Ścieżka do folderu z Dockerfile
          file: ./addon-i2c/Dockerfile # Ścieżka do Dockerfile
          # WAŻNA ZMIANA: Lista wszystkich architektur, aby stworzyć multi-arch manifest
          platforms: linux/aarch64,linux/amd64,linux/armhf,linux/armv7
          push: true # Wypycha obraz do GHCR
          tags: |
            # WAŻNA ZMIANA: Główny tag bez sufiksu architektonicznego.
            # To stworzy multi-arch manifest listę pod tym tagiem.
            ghcr.io/${{ github.repository_owner }}/i2c-addon:${{ env.ADDON_VERSION }}
            # Opcjonalnie: tag 'latest' również jako multi-arch manifest
            ghcr.io/${{ github.repository_owner }}/i2c-addon:latest
          cache-from: type=gha # Używa cache'u GitHub Actions dla szybszych kompilacji
          cache-to: type=gha,mode=max
