name: Build Singlearch ARM64

on:
  push:
    branches: [ main ]
    paths: [ 'addon-i2c/**' ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repo owner
        run: echo "REPO_OWNER_LOWERCASE=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Get addon version
        run: |
          ADDON_VERSION=$(jq -r '.version' ./addon-i2c/config.json)
          echo "ADDON_VERSION=$ADDON_VERSION" >> $GITHUB_ENV

      - name: Build singlearch ARM64
        run: |
          docker build \
            --platform linux/arm64/v8 \
            --build-arg BUILD_FROM=debian:bookworm-slim \
            -t ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/i2c-addon:${{ env.ADDON_VERSION }} \
            ./addon-i2c

      - name: Push image
        run: |
          docker push ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/i2c-addon:${{ env.ADDON_VERSION }}


#  create_manifest:
#    needs: build
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Log in to GitHub Container Registry
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Set lowercase repository owner
#        id: set_repo_owner_lowercase
#        run: echo "REPO_OWNER_LOWERCASE=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
#
#      - name: Get addon version from config.json (Manifest Job)
#        id: get_version_manifest
#        run: |
#          ADDON_VERSION=$(jq -r '.version' ./addon-i2c/config.json)
#          echo "ADDON_VERSION=$ADDON_VERSION" >> $GITHUB_ENV
#
#      - name: Create and push Docker manifest
#        run: |
#          MANIFEST_BASE=ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/i2c-addon
#          ADDON_VERSION=${{ env.ADDON_VERSION }}
#          ARCH_IMAGE="${MANIFEST_BASE}-aarch64:${ADDON_VERSION}"
#
#          echo "Tworzę manifest dla wersji: ${ADDON_VERSION}"
#          echo "Obraz źródłowy: ${ARCH_IMAGE}"
#
#          docker manifest create ${MANIFEST_BASE}:${ADDON_VERSION} ${ARCH_IMAGE}
#          docker manifest push ${MANIFEST_BASE}:${ADDON_VERSION}
