name: Build and Publish Addon

on:
  push:
    branches:
      - main
    paths:
      - 'addon-i2c/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Tylko architektura aarch64 (arm64)
          - arch: aarch64
            docker_platform: linux/arm64/v8

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository owner
        id: set_repo_owner_lowercase
        run: echo "REPO_OWNER_LOWERCASE=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        shell: bash

      - name: Get addon version from config.json
        id: get_version
        run: |
          ADDON_VERSION=$(jq -r '.version' addon-i2c/config.json)
          echo "ADDON_VERSION=$ADDON_VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Build and push Docker image for ${{ matrix.arch }}
        uses: docker/build-push-action@v5
        with:
          context: ./addon-i2c
          file: ./addon-i2c/Dockerfile
          platforms: ${{ matrix.docker_platform }}
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/i2c-addon-${{ matrix.arch }}:${{ env.ADDON_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_FROM=debian:bookworm-slim

  create_manifest:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository owner
        id: set_repo_owner_lowercase
        run: echo "REPO_OWNER_LOWERCASE=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        shell: bash

      - name: Get addon version from config.json
        id: get_version
        run: |
          ADDON_VERSION=$(jq -r '.version' addon-i2c/config.json)
          echo "ADDON_VERSION=$ADDON_VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Wait for images to be available
        run: sleep 15 # Odczekaj 15 sekund
        shell: bash

      - name: Create manifest list and push
        run: |
          MANIFEST_TAG=ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/i2c-addon:${{ env.ADDON_VERSION }}
          LATEST_TAG=ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/i2c-addon:latest

          IMAGES_TO_MANIFEST=(
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/i2c-addon-aarch64:${{ env.ADDON_VERSION }}
          )

          echo "Creating manifest for ${MANIFEST_TAG} with images: ${IMAGES_TO_MANIFEST[@]}"
          docker manifest create ${MANIFEST_TAG} ${IMAGES_TO_MANIFEST[@]}

          echo "Pushing manifest ${MANIFEST_TAG}"
          docker manifest push ${MANIFEST_TAG}

          echo "Creating manifest for ${LATEST_TAG} with images: ${IMAGES_TO_MANIFEST[@]}"
          docker manifest create ${LATEST_TAG} ${IMAGES_TO_MANIFEST[@]}

          echo "Pushing manifest ${LATEST_TAG}"
          docker manifest push ${LATEST_TAG}
        shell: bash
