name: Build and Publish Addon

on:
  push:
    branches:
      - main
    paths:
      - 'addon-i2c/**' # Monitoruj zmiany tylko w tym folderze
  workflow_dispatch:

permissions:
  contents: read
  packages: write # NADANIE UPRAWNIEŃ DO ZAPISU PAKIETÓW!

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64
            docker_platform: linux/arm64/v8

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository owner
        id: set_repo_owner_lowercase
        run: echo "REPO_OWNER_LOWERCASE=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Get addon version from config.json
        id: get_version
        run: |
          ADDON_VERSION=$(jq -r '.version' ./addon-i2c/config.json)
          echo "ADDON_VERSION=$ADDON_VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image for ${{ matrix.arch }}
        uses: docker/build-push-action@v5
        with:
          context: ./addon-i2c
          file: ./addon-i2c/Dockerfile
          platforms: ${{ matrix.docker_platform }}
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/i2c-addon-${{ matrix.arch }}:${{ env.ADDON_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_FROM=debian:bookworm-slim

#  create_manifest:
#    needs: build
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Log in to GitHub Container Registry
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Set lowercase repository owner
#        id: set_repo_owner_lowercase
#        run: echo "REPO_OWNER_LOWERCASE=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
#
#      - name: Get addon version from config.json (Manifest Job)
#        id: get_version_manifest
#        run: |
#          ADDON_VERSION=$(jq -r '.version' ./addon-i2c/config.json)
#          echo "ADDON_VERSION=$ADDON_VERSION" >> $GITHUB_ENV
#
#      - name: Create and push Docker manifest
#        run: |
#          MANIFEST_BASE=ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/i2c-addon
#          ADDON_VERSION=${{ env.ADDON_VERSION }}
#          ARCH_IMAGE="${MANIFEST_BASE}-aarch64:${ADDON_VERSION}"
#
#          echo "Tworzę manifest dla wersji: ${ADDON_VERSION}"
#          echo "Obraz źródłowy: ${ARCH_IMAGE}"
#
#          docker manifest create ${MANIFEST_BASE}:${ADDON_VERSION} ${ARCH_IMAGE}
#          docker manifest push ${MANIFEST_BASE}:${ADDON_VERSION}
