name: Build and Publish Addon

on:
  push:
    branches:
      - main
    paths:
      - 'addon-i2c/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # WAŻNE: Usunięto 'strategy.matrix.arch' - ten job uruchomi się teraz raz dla wszystkich platform.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get addon version from config.json
        id: get_version
        run: |
          ADDON_VERSION=$(jq -r '.version' addon-i2c/config.json)
          echo "ADDON_VERSION=$ADDON_VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./addon-i2c
          file: ./addon-i2c/Dockerfile
          # WAŻNA ZMIANA: Lista wszystkich architektur. Buildx stworzy multi-arch manifest.
          platforms: linux/aarch64,linux/amd64,linux/armhf,linux/armv7
          push: true
          tags: |
            # WAŻNA ZMIANA: Główny tag bez sufiksu architektonicznego.
            # To utworzy multi-arch manifest listę pod tym tagiem.
            ghcr.io/${{ github.repository_owner }}/i2c-addon:${{ env.ADDON_VERSION }}
            # Opcjonalnie: tag 'latest' również jako multi-arch manifest.
            ghcr.io/${{ github.repository_owner }}/i2c-addon:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
