name: Build and Publish Addon

on:
  push:
    branches:
      - main
    paths:
      - 'addon-i2c/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository owner
        id: set_repo_owner_lowercase
        run: echo "REPO_OWNER_LOWERCASE=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        shell: bash

      - name: Get addon version from config.json
        id: get_version
        run: |
          ADDON_VERSION=$(jq -r '.version' addon-i2c/config.json)
          echo "ADDON_VERSION=$ADDON_VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./addon-i2c
          file: ./addon-i2c/Dockerfile
          platforms: linux/aarch64,linux/amd64,linux/armhf,linux/armv7
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/i2c-addon:${{ env.ADDON_VERSION }}
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/i2c-addon:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # KLUCZOWA ZMIANA: Przekazujemy pełne nazwy obrazów bazowych dla każdej architektury
          # To jest najczęstszy sposób radzenia sobie z różnymi tagami per arch.
          build-args: |
            BUILD_FROM_LINUX_AARCH64=debian:bookworm-slim-arm64v8
            BUILD_FROM_LINUX_AMD64=debian:bookworm-slim-amd64
            BUILD_FROM_LINUX_ARMHF=debian:bookworm-slim-arm32v6
            BUILD_FROM_LINUX_ARMV7=debian:bookworm-slim-arm32v7
