name: Build Singlearch ARM64

on:
  push:
    branches: [ main ]
    paths: [ 'addon-i2c/**' ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get addon version
        run: |
          ADDON_VERSION=$(jq -r '.version' ./addon-i2c/config.json)
          echo "ADDON_VERSION=$ADDON_VERSION" >> $GITHUB_ENV

      - name: Set lowercase repo owner
        run: echo "REPO_OWNER_LOWERCASE=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push multiarch
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64/v8 \
            --build-arg BUILD_FROM=ghcr.io/home-assistant/{arch}-base-python:3.12 \
            -t ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/i2c-addon:${{ env.ADDON_VERSION }} \
            -t ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/i2c-addon:latest \
            --push \
            ./addon-i2c
